version: "3.3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
    - TZ=Europe/Samara
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always  
  
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - 8083:80
    volumes:
        - ./index.html:/usr/local/apache2/htdocs/index.html

  client:
    image: curlimages/curl:latest
    container_name: curlclient
    command: sh -c "while :; do curl "http://apache" 2>&1; echo; sleep 5; done"
    depends_on:
        - apache